name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
    paths:
      - "public/**"
  workflow_dispatch:   # يسمح بنشر يدوي عند الحاجة

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: noon-site
          directory: public
